[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200

lib_deps =
    https://github.com/johnrickman/LiquidCrystal_I2C.git
    adafruit/DHT sensor library @ ^1.4.7
    adafruit/Adafruit Unified Sensor @ ^1.1.15
    madhephaestus/ESP32Servo @ ^3.2.1

build_flags =
    -DCORE_DEBUG_LEVEL=0